### ISSUE TITLE
Any chanse for 1.16.5?

### ISSUE THREAD

**Issue by Niketats** [Prunoideae/ProbeJS#1]

**Comment by Prunoideae** [comment]
You can compile [this](https://github.com/Prunoideae/ProbeJS-Forge/tree/1.16.5) by yourself. This is quite a hobby project at that time, but I guess it should work, probably.

The codebase is quite different among 1.18.2, 1.18.1 and 1.16.5, I can't maintain or backport multiple versions of code simutaneously.

**Comment by Niketats** [comment]
![image](https://user-images.githubusercontent.com/68917520/164981864-12aa7d3c-61b0-4478-a043-c628e7f1e676.png)

**Comment by Niketats** [comment]
fixed via doing some stuff with JAVA_HOME

**Comment by Niketats** [comment]
hmmm, build successful, but build folder is empty

**Comment by Niketats** [comment]
help please
