### ISSUE TITLE
Uncaught exception happened in wrapper

### ISSUE THREAD

**Issue by dzej0** [Prunoideae/ProbeJS#10]
Issue when executing /probejs dump

[latest.log](https://github.com/Prunoideae/ProbeJS/files/10107447/latest.log)

**Comment by Prunoideae** [comment]
Problem is unknown, need to get what the console is printing. I thought catching and printing error in commands will be redirected to latest.log, but I'm wrong.

**Comment by dzej0** [comment]
The issue seems to be gone now, but i found a full log file from the same time that might help
[2022-11-28-4.log.log](https://github.com/Prunoideae/ProbeJS/files/10115114/2022-11-28-4.log.log)
