### ISSUE TITLE
Error when use /probejs dump

### ISSUE THREAD

**Issue by xb10123** [Prunoideae/ProbeJS#100]
When I use /probejs dump, it say that run into a error
![1](https://github.com/user-attachments/assets/366c5ba3-b751-41b3-9498-b16e97ab0e79)
[latest.log](https://github.com/user-attachments/files/16659274/latest.log)
Minecraft 1.20.1
Forge 47.2.0
Kubejs 6.5
Probejs 6.0.1

**Comment by Prunoideae** [comment]
😰

Sadly I have no idea about how to fix this, this looks like some very cursed recursion caused by some mod code mixing parameterized type and type variables (which I've already put an end on in type solution), so I can't think of any case making this happen again.
