### ISSUE TITLE
Erroer during dumping

### ISSUE THREAD

**Issue by 1Yui1** [Prunoideae/ProbeJS#101]
![Bild_2024-09-01_161237620](https://github.com/user-attachments/assets/3fb818b9-d5de-4d85-a0f7-34a7f1d37b0d)
 When i try to dump it, this error happens. When i install Rhizo, the game will crash (Dupemod)
![Bild_2024-09-01_161946332](https://github.com/user-attachments/assets/103b7cd2-dd3f-4219-80ba-bf2cd6c1a166)

**Comment by Prunoideae** [comment]
Please report to ProbeJS Legacy Github issue page
