### ISSUE TITLE
MC 1.19.2 probejs 4.1.5 error when dumping

### ISSUE THREAD

**Issue by genesy** [Prunoideae/ProbeJS#11]
[latest.log](https://github.com/Prunoideae/ProbeJS/files/10128687/latest.log)

running command on newly created single player world.

**Comment by Prunoideae** [comment]
I think it's a same issue with #9 but not updated to 1.19.2, will push a fix later.

**Comment by genesy** [comment]
any eta

**Comment by Prunoideae** [comment]
Not yet, I'm still rewriting code on document fetching, and later will have to deal with some other things.

**Comment by Prunoideae** [comment]
Fixed in 4.2.0.
