### ISSUE TITLE
[BUG] Dump error.

### ISSUE THREAD

**Issue by 854342681** [Prunoideae/ProbeJS#14]
**Description**
Error when run `/probejs dump` in minecraft.
**Version**
Minecraft: 1.18.2 
Forge: 40.1.92
Mod:probejs-4.0.0-fix3-forge
**Log**
[latest.log](https://github.com/Prunoideae/ProbeJS/files/10330858/latest.log)

**Comment by Prunoideae** [comment]
Can you send the `.vscode` folder under your `.minecraft` folder in zip format? This error is weird.

**Comment by 854342681** [comment]
我英文不太好，怕问题描述不清，都是国人所以我用中文说吧（）
我不知道如何复现这个问题，我在删除`kubejs`文件夹后重新运行游戏执行`/probejs dump`命令后可以正常dump了。
但是现在出现新的问题，我在vscode中的自动补全是残缺的，只有部分函数和物品可以自动补全。
![image](https://user-images.githubusercontent.com/62539940/210228379-e7f3f597-807d-49f5-abb8-2f9407834fe7.png)
![image](https://user-images.githubusercontent.com/62539940/210228466-10bd2874-7a5c-4f1f-8220-688069d39553.png)
[.vscode.zip](https://github.com/Prunoideae/ProbeJS/files/10331378/default.vscode.zip)

**Comment by Prunoideae** [comment]
补全是完整的，ProbeJS所推荐的KubeJS编写方式和KubeJS本身能做的有一些不同。

比如说如果你想要`minecraft`下的`crafting_shapeless`（也就是无序合成），你就得这样写：
```js
onEvent("recipes", event => {
    let { minecraft } = event.recipes
    minecraft.crafting_shapeless("farmersdelight:wheat_dough", [
        "pneumaticcraft:wheat_flour", "pneumaticcraft:wheat_flour", "pneumaticcraft:wheat_flour",
        "pneumaticcraft:wheat_flour", "pneumaticcraft:wheat_flour", "pneumaticcraft:wheat_flour",
        "water_bucket"
    ])
}
```
同样的，添加create的一些合成：
```js
onEvent("recipes", event => {
    let { create } = event.recipes;

    //Resin extracting
    create.compacting([Item.of("farmersdelight:tree_bark").withChance(0.2), Fluid.of("kubejs:resin", 100)], ["kubejs:resin"])
}
```

另外还有一些写法也被省略掉了，因为这是我个人所推崇的编写方式，另外有一些（比如说枚举的命名）是和LatvianModder讨论过后的结果。

我大概弄懂为什么前面的dump会出错了，不过这个问题不大，暂时不需要修。
