### ISSUE TITLE
Missing Server Events in `events.d.ts`

### ISSUE THREAD

**Issue by C0D3-M4513R** [Prunoideae/ProbeJS#16]
Now hear me out please:

I want to create Scripts for server side.
I want to have type annotations.

In the current state, I can only dump client side events and classes .
Server Side events and classes are not included.

If you wanted to implement it, by having dumps differ on Server vs on Client, go ahead:
The Plugin stopping the internal server in this scenario is not important, since you use the tool once to generate the type annotations, and then disable the mod.
So performance or Blocking the server doesn't even matter.

For my own use, I have just disabled the `.isSingleplayer()` annotations, to get around the current limitations and get at least some classes of the server.

Spoiler: It didn't work. 
The generated dump is not useful, and the serverside kubejs events are also not included.
Also there were ton's of mising class errors, because client classes are not in a server... duh!

Edit:
I modified some code a little, removing client sided references where they were causing exceptions, and I think I got a usable dump.
Server Side events are still not included though.

**Comment by C0D3-M4513R** [comment]
My main point is missing like all of the important events: item.right_click, item.left_click, item.crafted, player.* , etc.
There are many many more. Essentially I could check all events, that are marked as Server only [here](https://mods.latvian.dev/books/kubejs-legacy/page/list-of-all-events).


These have all been searched in events.d.ts:
<details><summary>Here is a full list of all missing events (`//` means the event is in the regular dumps, but not my server dump.)</summary>

- client.debug_info.left
- client.debug_info.right
- //client.generate_assets
- //client.logged_in
- client.logged_out
- //client.tick
- server.unload
- recipes.after_load
- level.unload
- level.explosion.pre
- level.explosion.post
- //player.logged_in
- player.logged_out
- //player.tick
- player.data_from_server.
- player.data_from_client.
- player.chat
- player.advancement
- player.inventory.opened
- player.inventory.closed
- player.inventory.changed
- player.chest.opened
- player.chest.closed
- //entity.death
- entity.attack
- //entity.drops
- //entity.check_spawn
- block.missing_mappings
- block.right_click
- block.left_click
- block.place
- block.break
- block.drops
- item.missing_mappings
- item.right_click
- item.right_click_empty
- item.left_click
- item.entity_interact
- item.pickup
- //item.tooltip
- item.crafted
- item.smelted
</details>
Btw.: Marking this as a "Dump" is really misleading, since you are downloading 99% of the information.

**Comment by C0D3-M4513R** [comment]
On another note: `net.minecraftforge.server.permission.PermissionAPI` is indexed by my server dump (types, as well as java(PermissionAPI)), but not by the regular Client dump.
I think, I will just use both dumps in parralell, for the best results.

**Comment by Prunoideae** [comment]
ProbeJS can only dump events that are fired before typing `/probejs dump` in 1.18.2, this design is carried out due to KubeJS's limits in event system (in 1.18.2). You should ensure that you fired events you mentioned before `/probejs dump`.

**Comment by Prunoideae** [comment]
This is already mentioned long before in the mod page on CurseForge.
![image](https://user-images.githubusercontent.com/24620047/215308237-f1e828c4-74bb-46c3-be17-01333faac6e7.png)
