### ISSUE TITLE
Missing Client events in `events.d.ts`

### ISSUE THREAD

**Issue by C0D3-M4513R** [Prunoideae/ProbeJS#17]
The following events are missing from `events.d.ts` when generating with:
Architectury: 4.10.88
Rhino: 1802.2.1-build.255
KubeJS: 1802.5.5-build.567
ProbeJS: 4.0.0-fix4
Using: jdk-18.0.2.1

- player.data_from_server.
- client.debug_info.left
- client.debug_info.right
- client.logged_out

**Comment by C0D3-M4513R** [comment]
[loaded](https://mods.latvian.dev/books/kubejs-legacy/page/eventjs) is also missing, but is a Startup event. Still putting it here tho.

**Comment by Prunoideae** [comment]
Closed as #16 .
