### ISSUE TITLE
Datapack: Structure Override is optional, not required

### ISSUE THREAD

**Issue by itsdinkd** [Prunoideae/ProbeJS#18]
![image](https://user-images.githubusercontent.com/35115304/215292539-3a997423-60b3-4d40-8c5d-d69b432a4ca2.png)

**Comment by Prunoideae** [comment]
ProbeJS does not have support for datapacks, the files it generated are for JS only. You should check somewhere else for datapack's support

**Comment by Prunoideae** [comment]
Do you have [this](https://marketplace.visualstudio.com/items?itemName=SPGoding.datapack-language-server) installed? It might be the cause.

**Comment by itsdinkd** [comment]
Ah yes i forgot I installed that extension. Thanks.
