### ISSUE TITLE
Sorry, it's me again

### ISSUE THREAD

**Issue by Niketats** [Prunoideae/ProbeJS#2]
can pls cheak closed issue

**Comment by Prunoideae** [comment]
I said that it is a hobby project at that time, and I'm not willing to give support to a random backport that I made without any deep thoughts. Simply reverting everything from Java 17 to 1.8 had caused enough trouble for me, and I don't want to diagnose weird things in lower version (which is not so dead yet but sure to be dead one day) for things which won't even get published in CurseForge.
