### ISSUE TITLE
Dump Error

### ISSUE THREAD

**Issue by Wolfkid200444** [Prunoideae/ProbeJS#21]
Getting this error while trying to dump

https://mclo.gs/BntYzGa

**Comment by Prunoideae** [comment]
The log is not complete, you need to send the complete log containing the crash information.

**Comment by Wolfkid200444** [comment]
https://mclo.gs/iNINlh1 Here is the full log

**Comment by Prunoideae** [comment]
The log you uploaded only has 25k lines, which is not containing the line where the report is dumped:

![image](https://user-images.githubusercontent.com/24620047/220609768-4fbdfc20-9f89-4bcb-a082-7c886ca95762.png)

Also, is ProbeJS really reporting a crash while dumping, and is files for type definitions were really not generated, or you just found that ProbeJS is spamming "warns" when dumping?
