### ISSUE TITLE
Probe removes ALL of KubeJS when uninstalled

### ISSUE THREAD

**Issue by FooterManDev** [Prunoideae/ProbeJS#22]
Hey, so I recently just removed Probe from my modpack because I wasn't using it, and in doing so RIPPED my entire KubeJS folder, removed everything back to default. I really need to know why this happened. All I did was:
Remove the JAR
Delete the two folders in the Kube folder related to VSC

**Comment by Prunoideae** [comment]
What two folders, ProbeJS will only generate one folder in the KubeJS folder (which is named `probe`), and a `.vscode` folder should be generated under the `.minecraft` folder.

Can you make sure that the file you removed is and only is named `probejs-4.3.0-forge.jar` or fabric version? It is obvious that the mod can do nothing after removal, I totally have no clues about what you're talking about.

**Comment by FooterManDev** [comment]
Correction
I deleted everything related to probe and vsc

**Comment by Prunoideae** [comment]
A removed mod can do nothing.
