### ISSUE TITLE
[Feature Suggest for 1.19.2] Datapack Grab

### ISSUE THREAD

**Issue by itsdinkd** [Prunoideae/ProbeJS#26]
I would love to see a way were I can pull the entire datapack in VSCode using ProbeJS by something like 
`$minecraft:diamond_helmet` for example.

once I hit that and auto complete, the entire datapack replaces that command. 

**Reason why I am suggesting this**
As a modpack developer, when we want to create recipes for a modded crafting type (say... AE2 Mana pool for example), there are multiple things that come into play, mainly the following;
* If you do not know it (or do not have a kubejs addon) you would need to open up the mod, go into its datapack and grab the datapack format for that crafting type

There also is the fact that lets say you just want to change a recipe here or there or learn what is in the recipe but do not want to have to go into REI/JEI to figure it out... This method allows modpack devs to not have to go into the game itself to learn recipes to make modifications but this gives us the ability to do everything outside of the game. Or cuts back on needing to dig through mod files. 

Once the datapack replaces the command, now we have the ability to easily turn it into a kubejs custom event.

**Comment by Prunoideae** [comment]
That is a genius idea, will add it soon.

**Comment by Prunoideae** [comment]
![2](https://user-images.githubusercontent.com/24620047/236611430-561ea389-ff7c-4622-8792-1ddd678cfe57.gif)

**Comment by itsdinkd** [comment]
OOOOH :D Youre amazing thank you.

The way you wrote out the shorthand is so much better than what I was thinking lol
