### ISSUE TITLE
ProbeJS doesn't work 

### ISSUE THREAD

**Issue by CraferOli** [Prunoideae/ProbeJS#28]
Forge 1.19.2

[latest.log](https://github.com/Prunoideae/ProbeJS/files/12109530/latest.log)

**Comment by Prunoideae** [comment]
Will be fixed in the next release.

**Comment by CraferOli** [comment]
Thank you for the quick support.
Do you happen to know when the next release is scheduled?

**Comment by Prunoideae** [comment]
In a few days, I need some time to see if I can have more updates.
