### ISSUE TITLE
Add support for grabbing Kube recipes

### ISSUE THREAD

**Issue by FooterManDev** [Prunoideae/ProbeJS#30]
Typing a hash (#) in VSC pulls up a bunch of datapacks, it'd be really awesome if this included recipes made in KubeJS so we don't have to go searching for old code if we need to copy something quickly.

**Comment by Prunoideae** [comment]
I don't think it would be a good idea, KubeJS creates recipes with a dynamic, unique id, if such recipes are also pulled, there'll be a lot of noise in the recipe. (Like `#kubejs:.../kjs_xxxxxx`)
