### ISSUE TITLE
ProbeJS stopped generating definitions for most of the events?

### ISSUE THREAD

**Issue by BackupCup** [Prunoideae/ProbeJS#33]
After some time using ProbeJS generated .vscode and probe folders i tried to regenerate them (deleting them and jsconfig first). It generated new ones, but now VSCode just can't find any definitions for most events (for example `event.recipes.create.sequenced_assembly` and so on). I suspect this might actually be an issue with VSCode but im not sure.

[latest.log](https://github.com/Prunoideae/ProbeJS/files/12300716/latest.log)

**Comment by Prunoideae** [comment]
Looks suspicious, can you try to F1 then restart TS language server?

Dumping should be deterministic between runs, probably a VSCode problem.

**Comment by BackupCup** [comment]
So, basically removing the kubejs scripts i had, dumping and then adding them back fixed the issue.

**Comment by Prunoideae** [comment]
Hmmm, might be related to how VSCode handles the project environment.
