### ISSUE TITLE
[1.19.2] Uncaught Exception happened in wrapper

### ISSUE THREAD

**Issue by TTFTCUTS** [Prunoideae/ProbeJS#34]
Posting whole log as requested, the relevant error is on line 4209: [log gist](https://gist.github.com/TTFTCUTS/10e680bee8f21762428b2af98a97839f)

Please save me from the ignorance of scripting blind 😭

**Comment by Prunoideae** [comment]
Oh... I got the remote docs written wrong.

**Comment by Prunoideae** [comment]
Should be fixed.
