### ISSUE TITLE
[1.18.2] Uncaught exception : Infinity is not a valid double value as per JSON specification

### ISSUE THREAD

**Issue by Yldales** [Prunoideae/ProbeJS#35]
Hi,

I get the following error when executing the **/probejs dump** command, using **probejs-4.0.0-fix4-forge.jar**.

> [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [CHAT] Uncaught exception happened in wrapper, please report to the Github issue with complete latest.log.

The complete error in the latest.log ([pastebin here](https://pastebin.com/raw/U2pcXVJn)) :

> [Server thread/INFO] [probejs/]: Checking docs timestamps...
> [Server thread/INFO] [probejs/]: Timestamps are matched (local = remote = 1690517104649), no need to update docs.
> [Server thread/ERROR] [probejs/]: **Infinity is not a valid double value as per JSON specification. To override this behavior, use GsonBuilder.serializeSpecialFloatingPointValues() method.**
> [Server thread/ERROR] [probejs/]: MC-BOOTSTRAP/com.google.gson@2.8.9/com.google.gson.Gson.checkValidFloatingPoint(Gson.java:390)
> [Server thread/ERROR] [probejs/]: MC-BOOTSTRAP/com.google.gson@2.8.9/com.google.gson.Gson$2.write(Gson.java:382)
> [Server thread/ERROR] [probejs/]: MC-BOOTSTRAP/com.google.gson@2.8.9/com.google.gson.Gson$2.write(Gson.java:368)
> [Server thread/ERROR] [probejs/]: MC-BOOTSTRAP/com.google.gson@2.8.9/com.google.gson.Gson.toJson(Gson.java:735)
> [Server thread/ERROR] [probejs/]: MC-BOOTSTRAP/com.google.gson@2.8.9/com.google.gson.Gson.toJson(Gson.java:714)
> [Server thread/ERROR] [probejs/]: MC-BOOTSTRAP/com.google.gson@2.8.9/com.google.gson.Gson.toJson(Gson.java:669)
> [Server thread/ERROR] [probejs/]: MC-BOOTSTRAP/com.google.gson@2.8.9/com.google.gson.Gson.toJson(Gson.java:649)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/probejs@4.0.0-fix4/com.probejs.formatter.formatter.jdoc.FormatterValue$PrimitiveFormatter.formatDocument(FormatterValue.java:42)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/probejs@4.0.0-fix4/com.probejs.formatter.formatter.jdoc.DocumentFormatter.format(DocumentFormatter.java:37)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/probejs@4.0.0-fix4/com.probejs.formatter.formatter.IFormatter.format(IFormatter.java:10)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/probejs@4.0.0-fix4/com.probejs.formatter.formatter.IFormatter.formatFirst(IFormatter.java:18)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/probejs@4.0.0-fix4/com.probejs.formatter.formatter.jdoc.FormatterField.formatDocument(FormatterField.java:33)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/probejs@4.0.0-fix4/com.probejs.formatter.formatter.jdoc.DocumentFormatter.format(DocumentFormatter.java:37)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/probejs@4.0.0-fix4/com.probejs.formatter.formatter.jdoc.FormatterClass.lambda$formatDocument$4(FormatterClass.java:87)
> [Server thread/ERROR] [probejs/]: java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
> [Server thread/ERROR] [probejs/]: java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> [Server thread/ERROR] [probejs/]: java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
> [Server thread/ERROR] [probejs/]: java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
> [Server thread/ERROR] [probejs/]: java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> [Server thread/ERROR] [probejs/]: java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
> [Server thread/ERROR] [probejs/]: java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
> [Server thread/ERROR] [probejs/]: java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> [Server thread/ERROR] [probejs/]: java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/probejs@4.0.0-fix4/com.probejs.formatter.formatter.jdoc.FormatterClass.formatDocument(FormatterClass.java:87)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/probejs@4.0.0-fix4/com.probejs.formatter.formatter.jdoc.DocumentFormatter.format(DocumentFormatter.java:37)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/probejs@4.0.0-fix4/com.probejs.formatter.formatter.FormatterNamespace.format(FormatterNamespace.java:21)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/probejs@4.0.0-fix4/com.probejs.formatter.formatter.IFormatter.formatString(IFormatter.java:14)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/probejs@4.0.0-fix4/com.probejs.compiler.DocCompiler.compileGlobal(DocCompiler.java:60)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/probejs@4.0.0-fix4/com.probejs.compiler.DocCompiler.compile(DocCompiler.java:381)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/probejs@4.0.0-fix4/com.probejs.ProbeCommands.lambda$register$1(ProbeCommands.java:69)
> [Server thread/ERROR] [probejs/]: MC-BOOTSTRAP/brigadier@1.0.18/com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/minecraft@1.18.2/net.minecraft.commands.Commands.m_82117_(Commands.java:234)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9957_(ServerGamePacketListenerImpl.java:1150)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_143628_(ServerGamePacketListenerImpl.java:1129)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_7388_(ServerGamePacketListenerImpl.java:1115)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(ServerboundChatPacket.java:30)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(ServerboundChatPacket.java:7)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/minecraft@1.18.2/net.minecraft.server.TickTask.run(TickTask.java:18)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:761)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689)
> [Server thread/ERROR] [probejs/]: TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261)
> [Server thread/ERROR] [probejs/]: java.base/java.lang.Thread.run(Thread.java:833)

Versions : 

- Minecraft 1.18.2
- Forge 40.2.10
- [KubeJS 1802.5.5 b569](https://legacy.curseforge.com/minecraft/mc-mods/kubejs/files/4377177)
- [Architectury API 4.11.93](https://legacy.curseforge.com/minecraft/mc-mods/architectury-api/files/4521465)
- [Rhino 1802.2.1 b255](https://legacy.curseforge.com/minecraft/mc-mods/rhino/files/4069880)
- [ProbeJS 4.0.0 fix4](https://legacy.curseforge.com/minecraft/mc-mods/probejs/files/4365860)

**Comment by Prunoideae** [comment]
Maybe you can make a pull request? Recently I'm super busy working on something.

**Comment by Yldales** [comment]
Yes, sure, if the proposed solution sounds good to you.
