### ISSUE TITLE
Dump error :3

### ISSUE THREAD

**Issue by kittech0** [Prunoideae/ProbeJS#4]
1.18.2 fabric btw

[crash-2022-06-29_18.11.43-server.txt](https://github.com/Prunoideae/ProbeJS/files/9013056/crash-2022-06-29_18.11.43-server.txt)
[crash-2022-06-29_18.11.43-server.txt](https://github.com/Prunoideae/ProbeJS/files/9013056/crash-2022-06-29_18.11.43-server.txt)

**Comment by Prunoideae** [comment]
Fixed in [latest release](https://github.com/Prunoideae/ProbeJS/releases/tag/v3.0.5-1.18.2-info) on Github.

Release on CurseForge will be rolled out later as more features get implemented.
