### ISSUE TITLE
[1.18.2] global.d.ts show error lines

### ISSUE THREAD

**Issue by EvanHsieh0415** [Prunoideae/ProbeJS#40]
![圖片](https://github.com/Prunoideae/ProbeJS/assets/74277414/4453bc17-c873-4470-a6ee-7ff15d496f0a)

logs: https://mclo.gs/MGCuHO8

source: https://discord.com/channels/303440391124942858/1168780532004433941/1168789258719469578

**Comment by pietro-lopes** [comment]
Yes, it is fabric related:

`redirect$zma000$fabric-transfer-api-v1$fabric_redirectMarkDirty` for example.

those - causes it to break

**Comment by Prunoideae** [comment]
Should be fixed already.
