### ISSUE TITLE
[1.20.1] Mixin transformation of net.minecraft.class_60 failed

### ISSUE THREAD

**Issue by TacoMonkey11** [Prunoideae/ProbeJS#43]
Crash Report: https://api.mclo.gs/1/raw/lbNHIVF

ProbeJS: 5.3.2
KubeJS: 2001.6.3-build.83+fabric

**Comment by Prunoideae** [comment]
Wait, it doesn't make sense, can you start the pack if you remove ProbeJS and run with KubeJS?

**Comment by Prunoideae** [comment]
https://static.wolfgirl.moe/drive/probejs-preview

Anyway, try to see if this fabric jar works for you, if it does, then probably some fabric mapping problem.

**Comment by TacoMonkey11** [comment]
It was a simple user error problem, I was using the latest github release, which I didn't realize was for 1.19.2. It would be very useful if the Minecraft version compatibility was updated in the fabric.mod.json (It currently says >=1.18.2)
