### ISSUE TITLE
[1.20.1] Silent Gear causes global.d.ts to contain invalid Syntax

### ISSUE THREAD

**Issue by DeinAlbtraumTV** [Prunoideae/ProbeJS#46]
Dumping with Silent Gear installed causes the dumped global.d.ts file to contain multiple of the following errors (replacing the / with a _ might be all that is needed here):

```js
class Compounding/fabricSilentgear extends Internal.JsonRecipeJS {
}
```

As you can see, the / in the class name is invalid syntax in JS.

Class list that i noticed this happening on:
- Compounding/fabricSilentgear
- Compounding/gemSilentgear
- Compounding/metalSilentgear
- Pressing/materialSilentgear
- Salvaging/gearSilentgear
- Salvaging/compoundPartSilentgear
- Smithing/coatingSilentgear
- Smithing/upgradeSilentgear

This is using probejs-5.5.0-forge and kubejs-forge-2001.6.4-build.111 on forge 47.2.17 with the following kubejs extensions:
- morejs-forge-1.20.1-0.5.0
- kubejsadditions-forge-4.0.1
- kubejs-create-forge-2001.2.5-build.2
- lootjs-forge-1.20.1-2.10.4
- ponderjs-1.20.1-1.3.0

Although these extensions shouldn't impact the dumping of Silent Gear classes

**Comment by DeinAlbtraumTV** [comment]
Looking closer this might be a general issue with how recipe type names are handled. The broken silent gear recipe classes seem to contain a / in the type name:
https://github.com/SilentChaos512/Silent-Gear/blob/c4b219d184c763a816f5222d0d52c1e5de67c255/src/generated/resources/data/silentgear/recipes/pressing/material/sheet_metal.json#L2

This shouldn't be a problem though as we can also have slashes in recipe IDs/tags

**Comment by Prunoideae** [comment]
Will be fixed with an unpublished release.
