### ISSUE TITLE
[1.20.1] Random Brackets in global.d.ts

### ISSUE THREAD

**Issue by DeinAlbtraumTV** [Prunoideae/ProbeJS#47]
I noticed that i have 2 random closing curly brackets in my global.d.ts.

One before the definition of a bunch of MC types:

```js
} //this has no opening bracket and causes an error
    type ArrayOrSelf<T> = T[] | T
    type JavaClass = "net.minecraft.util.ProgressListener" // ...
```

and another one closing after that type block, right before the definition of the log4j.core.time namespace:

```js
    type CommandArgumentType = "brigadier:bool" // ...
} //this also has no opening bracket and because of that causes an error
declare namespace org.apache.logging.log4j.core.time {
```

This is using probejs-5.5.0-forge and kubejs-forge-2001.6.4-build.111 on forge 47.2.17 with the following kubejs extensions:

- morejs-forge-1.20.1-0.5.0
- kubejsadditions-forge-4.0.1
- kubejs-create-forge-2001.2.5-build.2
- lootjs-forge-1.20.1-2.10.4
- ponderjs-1.20.1-1.3.0

I can provide the global.d.ts file if needed, not going to upload that without it being required (over 200k lines lol)

Great mod though, keep up the good work!

**Comment by Prunoideae** [comment]
Probably is fixed with an unpublished update.
