### ISSUE TITLE
VSCode -> when installing the extension, an error is displayed

### ISSUE THREAD

**Issue by RadostinDinov** [Prunoideae/ProbeJS#48]
Installing the extension throws an error in VSCode:
![image_2023-12-12_165929075](https://github.com/Prunoideae/ProbeJS/assets/118980844/f11ac160-d0d5-4a17-959c-1158282a0e69)

I have the mod in the game, but when I open skripts in folder server-scripts, no autocompletion and suggestions

**Comment by Prunoideae** [comment]
Did you dump the files by using `/probejs dump`? Also the extension only support 1.19.2+.

**Comment by RadostinDinov** [comment]
Yes, I dumped. I am using 1.20.1. I have the three points completed and checked:
1. Many JSON files started with "probe" in the .vscode folder are under your .minecraft folder.
2. There is a "probe" folder under the KubeJS folder, and many files ending with ".d.ts" are in the folder.
3. All ".d.ts" files don't have syntax errors indicated by VSCode.

**Comment by RadostinDinov** [comment]
Is it a problem that I'm loading the mods via CurseForge?

C:\Users\<user>\curseforge\minecraft\Instances\<custom_modpack_name>\kubejs\server_scripts

**Comment by Prunoideae** [comment]
You should open the folder where a .vscode is generated, usually the parent folder of `kubejs`/`mods`. Like this:
![image](https://github.com/Prunoideae/ProbeJS/assets/24620047/79f0bb3a-cb1f-4901-8a59-31745e452c06)

**Comment by RadostinDinov** [comment]
Thank you very much! Appreciate it. Please, add this in the documentation or the description, cuz when not using the .minecraft it is confusing. Please, mention that the VSCode should open the folder where .vscode is located :)
