### ISSUE TITLE
1.16 unofficial continuation?

### ISSUE THREAD

**Issue by ZZZank** [Prunoideae/ProbeJS#49]
I made a [fork](https://github.com/ZZZank/ProbeJS-Forge) of ProbeJS based on [ProbeJS-Forge-1.16.5](https://github.com/Prunoideae/ProbeJS-Forge) , can I publish it on CurseForge/Modrinth and label it as "unofficial continuation" of ProbeJS for 1.16.5?

**Comment by Prunoideae** [comment]
No problem, you can do as you like.
