### ISSUE TITLE
What is the VSCode theme in the example?

### ISSUE THREAD

**Issue by rsp4jack** [Prunoideae/ProbeJS#5]
Nice mod, and nice VSCode theme! What is the VSCode in [the example](https://github.com/Prunoideae/ProbeJS/raw/1.18.2/examples/3.gif)?
![The example](https://github.com/Prunoideae/ProbeJS/raw/1.18.2/examples/3.gif)

**Comment by Prunoideae** [comment]
It's Material Palenight in the Material Theme, which can be downloaded from the extension page.

Personally speaking, it's my favorite theme, so I'm glad that you like it too.
