### ISSUE TITLE
crashes with latest version of kubejs on 1.20.1 (2001.6.4-build.120)

### ISSUE THREAD

**Issue by MikeyPantsOn** [Prunoideae/ProbeJS#51]
[debug.log](https://gnomebot.dev/paste/1195487309005586472)
[latest.log](https://gnomebot.dev/paste/1195487309005586472)

no idea what causes it, it crashes on first load with no scripts as well..

**Comment by Prunoideae** [comment]
Looks like there are some mixin problems but the log did not provide any useful information about it.

**Comment by MikeyPantsOn** [comment]
> Looks like there are some mixin problems but the log did not provide any useful information about it.

in the kubejs discord i was told to delete the config file and it seemed to fix it..
