### ISSUE TITLE
Uncaught exception happened in wrapper

### ISSUE THREAD

**Issue by Strange05** [Prunoideae/ProbeJS#52]
Every time i try to do a `probejs dump` i get this `uncaught exception happened in wrapper`. Just reporting 
[latest.log](https://github.com/Prunoideae/ProbeJS/files/13930777/latest.log)

**Comment by Prunoideae** [comment]
Change the `docsTimestamp` field in the `kubejs/config/probejs.json` to `0`. This is caused by me accidentally set timestamp to `-1` in the cache clearing.
