### ISSUE TITLE
Error occurred while rendering images

### ISSUE THREAD

**Issue by Nycto97** [Prunoideae/ProbeJS#54]
![image](https://github.com/Prunoideae/ProbeJS/assets/83367226/c7d8ca90-1808-4a19-82aa-9a298109b500)

[latest.log](https://github.com/Prunoideae/ProbeJS/files/14106963/latest.log)

**Comment by Prunoideae** [comment]
Probably won't be fixed as the rendering code is not something I know well of. The dumping itself works fine so you still get code completions, I suppose.
