### ISSUE TITLE
Modrinth release?

### ISSUE THREAD

**Issue by lonevox** [Prunoideae/ProbeJS#55]
Could this be uploaded to Modrinth? It is one of the only mods in my pack that isn't on Modrinth so an upload there would be awesome! If a Modrinth release isn't planned, is it okay to distribute your jars in my pack (the actual jar file, not a link)?

**Comment by Prunoideae** [comment]
The mod is currently being reviewed. Got too many things to do previously.

**Comment by Prunoideae** [comment]
Published at https://modrinth.com/mod/probejs
