### ISSUE TITLE
Email for security vulnerability disclosure

### ISSUE THREAD

**Issue by Reabstraction** [Prunoideae/ProbeJS#60]
I have found a security vulnerability in ProbeJS, and want to report it

What email can I send the details to?

**Comment by ZZZank** [comment]
`jlijh@connect.ust.hk`, according to Prunoideae's github page

**Comment by Prunoideae** [comment]
I wonder what kind of security vulnerability it is.

**Comment by n0099** [comment]
https://github.com/Prunoideae/ProbeJS/compare/20999319d40ce9ef69cf9025273dd84b72ac6420%5E1...v6.0.1
