### ISSUE TITLE
Mixin-related Crash on 1.19.2

### ISSUE THREAD

**Issue by tizu69** [Prunoideae/ProbeJS#7]
KubeJS ver: [Forge 1802.5.5-build.554](https://www.curseforge.com/minecraft/mc-mods/kubejs/files/4060538)
ProbeJS ver: 4.0.0
Minecraft 1.19.2

Crash logs (scroll to bottom): https://mclo.gs/4ztcbAG

**Comment by Prunoideae** [comment]
The version on CurseForge is not usable with KubeJS 6 (And it's in the 1.19.2-obselete branch), you can wait for KubeJS to end its alpha, and the rewritten version will be pushed on CurseForge.
