### ISSUE TITLE
[Fabric 1.20.1] Stop using glob references

### ISSUE THREAD

**Issue by Martmists-GH** [Prunoideae/ProbeJS#72]
Glob references are not supported by IntelliJ and other Jetbrains IDEs.

![image](https://github.com/Prunoideae/ProbeJS/assets/16361449/c95347d7-7c0b-4eae-a045-ff5972a1bfdb)

**Comment by Prunoideae** [comment]
Check out v7.0.1 which completely rewrote the project structure.

**Comment by Martmists-GH** [comment]
I cannot find a 7.0.1 release for Fabric 1.20.1
