### ISSUE TITLE
[Fabric 1.20.1] Abstract methods are erroneously generated on interfaces

### ISSUE THREAD

**Issue by Martmists-GH** [Prunoideae/ProbeJS#74]
![Screenshot_20240624_152356](https://github.com/Prunoideae/ProbeJS/assets/16361449/e4313b5f-350e-4d0c-bdc2-840151b35e3f)

**Comment by Prunoideae** [comment]
It should be fixed already on v7.0.0, though that version has some other issues.

**Comment by Martmists-GH** [comment]
Unfortunately I don't see a 7.0.0 release for Fabric 1.20.1, so the issue should stay open.
