### ISSUE TITLE
[1.21] Crash on startup with new KubeJS

### ISSUE THREAD

**Issue by NielsPilgaard** [Prunoideae/ProbeJS#79]
I crash on startup after updating KubeJS

- kubejs-2100.7.0-build.79
- ProbeJS-7.1.1
- Neoforge-21.0.53

Crash: https://gist.github.com/NielsPilgaard/e9805070471a40bc450764a0ede58729

**Comment by Prunoideae** [comment]
Should be fixed with 7.2.1 release.
