### ISSUE TITLE
Crashing with Xaero's Minimap

### ISSUE THREAD

**Issue by txnitxnichopper** [Prunoideae/ProbeJS#8]
Something's fucked when Xaero's Minimap is installed, uninstalling got the dump done fine.

![image](https://user-images.githubusercontent.com/67132971/201269827-aa1c2ff5-84c7-47f9-9eca-c6174d8a25ba.png)

**Comment by Prunoideae** [comment]
For weird reason the class is not getting loaded, this was fixed before, but brought out again due to the `ClassInfo` resolving is rewritten. Will fix later.

**Comment by Prunoideae** [comment]
It's a problem occurring inside Xaero's Minimap itself, I don't think it would be a good way to fix on our side.

But maybe it will be fixed sometime later... I've got reports on StructureGel or something crashing like this too
