### ISSUE TITLE
An unexpected error occurred  when trying to execute /probejs dump

### ISSUE THREAD

**Issue by Fr0z9** [Prunoideae/ProbeJS#81]
I don`t know why this happened. The screen just show me these messages. After this I still try to edit my js file, it seems that just some of the tips can be used, not all. How can I make it work correctly? And if I need offer some more information?
![image](https://github.com/Prunoideae/ProbeJS/assets/110195211/28f4f965-5d28-4abc-bad9-248385a4e53a)
![image](https://github.com/Prunoideae/ProbeJS/assets/110195211/fd643cf5-5f96-40f0-831d-431224061c4b)

**Comment by Prunoideae** [comment]
No, it just won't work because there's a very specific problem in KubeJS's reflection helper which that I can fix with some handling, but I don't want to continue on the codebase anymore.

**Comment by snoff4** [comment]
Is there anything that we as developers could do to work around it? Or even fix it?

Do you have any tips or strategies for diagnosing and debugging these  exceptions. I happen to have encountered this issue myself.
