### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by ChloePrime** [Prunoideae/ProbeJS#82]
The generated file has over 140MB of file size,
making VSCode unusably laggy.
[latest.log of the game](https://mclo.gs/qfGJRp9)

**Comment by Prunoideae** [comment]
It is only improved in 1.21. You can use v6.1.0 but I wonder that's still laggy.

**Comment by ChloePrime** [comment]
Where is 6.1.0?
I can only find 6.0.1 and 6.0.1 has error when dumping

**Comment by Prunoideae** [comment]
Then it's 6.0.1 which I won't fix anything either
