### ISSUE TITLE
[1.18.2][ProbeJS 4.0.0-fix1-forge]Crash when running /probejs dump

### ISSUE THREAD

**Issue by Anoyomouse** [Prunoideae/ProbeJS#9]
Hi

I'm trying to generate mapping data for FTB Stoneblock (latest version 1.3.0). default modpack.

Comes up with `Uncaught exception happened in wrapper, please report to the Github issue with complete latest.log`

Latest log: 
[latest.log](https://github.com/Prunoideae/ProbeJS/files/10029842/latest.log)

**Comment by Prunoideae** [comment]
This is weird, why there's no printed stack trace when it throws an error? Can you check in stdout (like the console output in MMC)?

**Comment by Anoyomouse** [comment]
Found it 

It looks like it's crashing because Stoneblock 3 is using REI, and not JEI for it's item list, which is causing your probejs to collapse

[console.log](https://github.com/Prunoideae/ProbeJS/files/10049259/console.log)

**Comment by ghost** [comment]
I'm getting same Uncaught exception error. REI is definitely the issue. Tested with just KubeJS, ProbeJS, and then added REI to reproduce issue. Is there any plan for a fix? Any workaround?

**Comment by Prunoideae** [comment]
I think I understand how to fix it, but first I need to find some time to start working on it.

**Comment by ghost** [comment]
@Prunoideae Still getting same thing with only Architectury API, Cloth config, KubeJS, ProbeJS, REI, REI Plufin Compat, and Rhino. Not sure what you need but attached is latest.log. Not sure what you need is it just the latest.log?

**Comment by Prunoideae** [comment]
> @Prunoideae Still getting same thing with only Architectury API, Cloth config, KubeJS, ProbeJS, REI, REI Plufin Compat, and Rhino. Not sure what you need but attached is latest.log. Not sure what you need is it just the latest.log?

This is weird, I tried to catch error there to fallback to a default value when it's errored, but it didn't work for some reason if the error persists. Please send the console output with the fix2 installed.

**Comment by Prunoideae** [comment]
I know where the problem is, will push a fix later, multiple problems are occurring at once

**Comment by Prunoideae** [comment]
Fix pushed as `fix2` on CurseForge.
