### ISSUE TITLE
/probejs dump crashed game

### ISSUE THREAD

**Issue by wolfieboy09** [Prunoideae/ProbeJS#90]
![image](https://github.com/user-attachments/assets/bf01e929-99f8-417d-b555-fda07b8d1d92)

Version: 7.0.1 for 1.20.1

![image](https://github.com/user-attachments/assets/5b81d749-772f-4f3b-8485-c975a644b9f9)
Then why release 7.x 🤣

**Comment by Prunoideae** [comment]
I don't know either, but the fact is that I don't want to deal with 6.x codebase anymore because it's not rewritten and has a lot of problems, and I don't want to deal with 7.x codebase in 1.20.1 because the 7.x is for 1.21+.
