### ISSUE TITLE
VS Code AggregateError and failing connection

### ISSUE THREAD

**Issue by CauaSCP** [Prunoideae/ProbeJS#91]
No matter what I, even restarting game then restarting Code still getting this issue:
![ERROR](https://github.com/user-attachments/assets/b454ecdc-8182-4284-8e1f-7cf88ca6821a)

**Comment by Prunoideae** [comment]
https://github.com/Prunoideae/ProbeJS/issues/85

**Comment by CauaSCP** [comment]
> #85

[My Response in that issue](https://github.com/Prunoideae/ProbeJS/issues/85#issuecomment-2243202211)
